export const COLORS = {
  bg: "#0d0d0f",
  surface: "#141416",
  surface2: "#1c1c1f",
  border: "#2a2a2e",
  accent: "#e8c547",
  accentDim: "#b89c30",
  rust: "#ce422b",
  cpp: "#00599c",
  ocaml: "#f08800",
  lean: "#2d5fa0",
  french: "#002395",
  spanish: "#c60b1e",
  golf: "#2d7a3a",
  gym: "#7b3fa0",
  omscs: "#555",
  text: "#e8e8e8",
  textDim: "#888",
  textFaint: "#555",
};

export const DEFAULT_TYPE_META = {
  prog: { color: COLORS.rust, label: "Programming" },
  language: { color: COLORS.french, label: "Languages" },
  omscs: { color: COLORS.omscs, label: "OMSCS" },
  gym: { color: COLORS.gym, label: "Gym" },
  golf: { color: COLORS.golf, label: "Golf" },
  work: { color: "#444", label: "Work" },
  routine: { color: "#333", label: "Life" },
  flex: { color: COLORS.ocaml, label: "Flex" },
  read: { color: COLORS.lean, label: "Reading" },
  free: { color: "#336", label: "Free" },
  sleep: { color: "#222", label: "Sleep" },
  music: { color: "#c4732a", label: "Music" },
  social: { color: "#2a7a8a", label: "Social" },
  oss: { color: "#5a9a3a", label: "Open Source" },
  sports: { color: "#8a5a2a", label: "Sports" },
};
